version: '3.7'

services:
    web:
        build:
            context: .
        ports:
            - 8000:8000
        volumes:
            - ./api:/home/TODO/api
            - ./scripts:/home/TODO/scripts
            - ./todo:/home/TODO/todo
            - ./variables:/home/TODO/variables
        env_file: 
            - ./variables/web.env
        depends_on:
            - db
    
    db:
        image: postgres:12-alpine
        volumes: 
            - postgres_data:/var/lib/postgres/data/
        env_file:
            - ./variables/db.env

volumes: 
    postgres_data: